---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: test

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[pgbouncer::default]
      - recipe[test]
    attributes:
        #    verifier:
        #      inspec_tests:
        #        - path: test/smoke/default
        #
